"""add metabase_password

Revision ID: c44e7ec7eecd
Revises: 003
Create Date: 2026-01-06 11:24:52.584911

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'c44e7ec7eecd'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dashboard_versions_id'), table_name='dashboard_versions')
    op.drop_table('dashboard_versions')
    op.drop_table('workspace_users')
    op.add_column('dashboards', sa.Column('metabase_dashboard_name', sa.String(), nullable=False))
    op.add_column('dashboards', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('dashboards', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('dashboards', sa.Column('embedding_params', sa.JSON(), nullable=True))
    op.alter_column('dashboards', 'workspace_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('dashboards_created_by_id_fkey'), 'dashboards', type_='foreignkey')
    op.drop_constraint(op.f('dashboards_workspace_id_fkey'), 'dashboards', type_='foreignkey')
    op.create_foreign_key(None, 'dashboards', 'workspaces', ['workspace_id'], ['id'])
    op.drop_column('dashboards', 'name')
    op.drop_column('dashboards', 'created_by_id')
    op.add_column('users', sa.Column('metabase_password', sa.String(), nullable=True))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'full_name')
    op.add_column('workspaces', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('workspaces', sa.Column('metabase_collection_name', sa.String(), nullable=True))
    op.add_column('workspaces', sa.Column('metabase_group_name', sa.String(), nullable=True))
    op.add_column('workspaces', sa.Column('database_id', sa.Integer(), nullable=True))
    op.add_column('workspaces', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('workspaces', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('workspaces', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_column('workspaces', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.alter_column('workspaces', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('workspaces', 'updated_at')
    op.drop_column('workspaces', 'is_active')
    op.drop_column('workspaces', 'database_id')
    op.drop_column('workspaces', 'metabase_group_name')
    op.drop_column('workspaces', 'metabase_collection_name')
    op.drop_column('workspaces', 'description')
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('users', 'metabase_password')
    op.add_column('dashboards', sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dashboards', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'dashboards', type_='foreignkey')
    op.create_foreign_key(op.f('dashboards_workspace_id_fkey'), 'dashboards', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('dashboards_created_by_id_fkey'), 'dashboards', 'users', ['created_by_id'], ['id'])
    op.alter_column('dashboards', 'workspace_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('dashboards', 'embedding_params')
    op.drop_column('dashboards', 'is_public')
    op.drop_column('dashboards', 'description')
    op.drop_column('dashboards', 'metabase_dashboard_name')
    op.create_table('workspace_users',
    sa.Column('workspace_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('workspace_users_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('workspace_users_workspace_id_fkey'), ondelete='CASCADE')
    )
    op.create_table('dashboard_versions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dashboard_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], name=op.f('dashboard_versions_dashboard_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('dashboard_versions_pkey'))
    )
    op.create_index(op.f('ix_dashboard_versions_id'), 'dashboard_versions', ['id'], unique=False)
    # ### end Alembic commands ###